function [c, ceq] = torque_constraint(PID, model)
% torque_constraint - A function to enforce torque limits in a PID-based control system.
%
% This function calculates the inequality constraints for a PID controller
% by simulating a model and ensuring that the torque values generated by the
% controller do not exceed a specified maximum or minimum limit. The function
% returns the constraints (c) as an array where violations of the bounds result
% in nonzero values. Equality constraints (ceq) are not used in this case.
%
% Input:
%   PID  - A vector containing the PID controller parameters [kp, kd, ki].
%   model - The name or path of the Simulink model to simulate.
%
% Output:
%   c    - Inequality constraints (torque values must stay within specified bounds).
%   ceq  - Equality constraints (none in this function).
%
% The torque control values are extracted from the simulation, and the norm of 
% the torque is compared against the set maximum and minimum torque limits.

    % Extract PID parameters
    kp = PID(1);
    kd = PID(2);
    ki = PID(3);

    % Set PID values in the workspace
    assignin('base', 'kp', kp);
    assignin('base', 'kd', kd);
    assignin('base', 'ki', ki);

    % Define the torque bounds
    torque_max_limit = 1e-2;  % Max torque limit
    torque_min_limit = -1e-2; % Min torque limit

    % Run the Simulink model
    simOut = sim(model);

    % Extract the torque control values from the simulation output
    torque_control = simOut.get('torque_control');
    
    % Initialize the inequality constraint (c) and equality constraint (ceq)
    c = [];  % No equality constraints
    ceq = []; % No equality constraints

    % Loop through the torque control signals and check if they exceed the bounds
    for i = 1:size(torque_control, 1)
        torque_vec = torque_control(i, :);  % Extract the torque vector at each time step
        torque_norm = norm(torque_vec);     % Calculate the norm of the torque vector

        % Add constraints to ensure torque norm is within the bounds
        % We want to enforce:
        % torque_min_limit <= torque_norm <= torque_max_limit

        % Upper bound constraint: torque_norm <= torque_max_limit
        % This will create a constraint that is violated if the torque exceeds the upper bound
        c = [c; torque_norm - torque_max_limit];

        % Lower bound constraint: torque_norm >= torque_min_limit
        % This will create a constraint that is violated if the torque is less than the lower bound
        c = [c; torque_min_limit - torque_norm];
    end
end
